export const happyDogPhrases = [
    "Woof! I'm one happy pup!",
    "Life is pawsome when you're a dog like me.",
    "Bark, wag, repeat — that's my motto!",
    "Can you see my tail wagging with joy?",
    "I'm so excited, I can't stop barking!",
    "I love playtime and belly rubs!",
    "Woof-woof! Let's go on an adventure together!",
    "Nothing makes me happier than a tasty treat.",
    "My tail is wagging like crazy. I'm in pure bliss!",
    "I'm a dog on cloud nine. Life is wag-tastic!",
    "Every day is a new tail-wagging adventure!",
    "I'm the happiest pup in the whole wide world!",
    "Did someone say 'walk'? Count me in!",
    "Sniffing the world around me brings me so much joy.",
    "Treats, treats, and more treats! Oh, the joy of it all!",
    "I've got a wag for every occasion. Watch me go!",
    "Running freely with the wind in my fur is pure happiness.",
    "I'm living my best doggie life. Can't you see the joy in my eyes?",
    "I've got a whole lot of love to give. Come get some cuddles!",
    "The sound of laughter makes me wiggle with happiness.",
    "Sunshine, grass, and a ball to chase. Life is perfect!",
    "I've got a heart full of love and a tail that won't stop wagging.",
    "Chasing my own tail? It's all part of the happy dog experience!",
    "I'm wagging my tail so hard, I might just take off!",
    "Licking your face is my way of saying 'I love you!'",
    "Happy dog, happy life. It's as simple as that!",
    "Being by your side is the ultimate happiness for me.",
    "I've got so much energy, I could play fetch all day long!",
    "A good belly rub can turn any day into a great one.",
    "Jumping for joy is my specialty. Want to join in?",
    "The world is full of fascinating smells. Let's explore them together!",
    "With every wag of my tail, I'm spreading happiness all around.",
    "Catching a frisbee mid-air? Now that's what I call pure bliss!",
    "I'm a happy-go-lucky dog, ready to make memories with you.",
    "Did someone say 'treat'? I'm all ears and ready to please!",
    "Rolling around in the grass is my version of pure joy.",
    "I'm a dog with a heart full of love and a nose full of scents.",
    "Belly up for a belly rub session! It's the best feeling ever.",
    "I'm wagging my tail so much, I might just lift off the ground!",
    "Playtime is the best time! Let's fetch, chase, and have a blast!",
    "Happiness is a warm cuddle from someone you love. Can I have one?",
    "A good game of tug-of-war is enough to make my tail wag uncontrollably.",
    "When I see you, my tail becomes a blur. That's how happy I am!",
    "Wiggling my butt is my way of saying 'I'm delighted to see you!'",
    "I may be small, but my happiness is larger than life!",
    "I'm not just a dog, I'm a ball of pure joy and happiness.",
    "A day filled with treats, play, and love is my definition of heaven.",
    "I may be covered in fur, but underneath, I'm all smiles and happiness.",
    "I'm a tail-wagging, tongue-lolling, happy-go-lucky kind of dog!",
    "Every day is a new opportunity for wagging, chasing, and being a happy dog!",
    "I've got so much love in my heart, and I can't wait to share it with you.",
    "I'm a tail-wagging machine! Life is amazing!",
    "Woof! Happiness is my middle name!",
    "I'm a happy dog on a mission to spread joy!",
    "Bark, bark, hooray! I'm living my best doggy life!",
    "Nothing can dampen my spirits. I'm a bundle of joy!",
    "Wagging my tail is my way of saying 'I love life!'",
    "I'm a furry ball of happiness, ready to brighten your day!",
    "Bark-tastic adventures await! Let's make memories!",
    "Every day is a new opportunity for wagging and play!",
    "Happiness radiates from my heart and through my wagging tail.",
    "I've got a grin from ear to ear. Life is fantastic!",
    "Woof! Life's too short to be anything but happy!",
    "I'm a pup filled with pure delight. Can you see it in my eyes?",
    "Bark with me if you're ready for a day filled with joy!",
    "I'm on cloud nine, basking in the happiness that surrounds me.",
    "The world is full of wonder, and I'm here to embrace it!",
    "Wagging my tail is my way of dancing to the rhythm of joy.",
    "I'm wagging my tail like crazy. Can you feel the happiness too?",
    "Bark-yeah! Happiness is contagious, so let's spread it together!",
    "Life is a never-ending game of fetch, and I'm loving every moment!",
    "I've got a heart full of love and a spirit that can't be tamed.",
    "Woof! I'm a happy dog with a zest for life!",
    "Every day is a new chance to chase happiness and wag my tail!",
    "I'm bounding with joy and ready to seize the day!",
    "Bark, wag, repeat — it's the secret to my happy dog life!",
    "I'm a pup on a mission to collect smiles and wagging tails!",
    "Happiness is my fuel, and it keeps my tail wagging all day long!",
    "Woof-woof! Let's celebrate life and make every moment count!",
    "I'm a bundle of energy and happiness, ready for anything!",
    "Bark if you're happy! Let's create a symphony of joy together!",
    "I'm living life in full color, with a wag and a smile!",
    "Happiness is my superpower, and I'm here to share it with you!",
    "Woof! I'm so happy, I could do a doggy dance right now!",
    "I'm a pup of many tail-wags and endless cuddles. Life is grand!",
    "Bark your heart out and let the world know you're happy!",
    "I'm chasing joy like it's the best game of fetch ever!",
    "Happiness fills my heart and spills out in wagging tail wiggles.",
    "Woof-woof! I'm a happy dog, and I'm ready to conquer the day!",
    "I've got a spring in my step and a smile on my snout. Life is woof-tastic!",
    "Bark if you love belly rubs and all things happy!",
    "I'm a tail-wagging guru, spreading happiness wherever I go!",
    "I'm a happy dog with a heart full of love and a soul full of playfulness!",
    "Woof! I'm chasing happiness like it's the most exciting game of all!",
    "Life is like a never-ending belly rub. It's pure bliss!",
    "I'm wagging my tail so hard, I might just take off! Life is amazing!",
    "Bark with joy and gratitude, for each day is a precious gift!",
    "I'm a pup with an attitude of gratitude. Happiness is my mantra!",
    "I'm on a constant happiness high. Life is too pawsome to be anything else!",
    "Woof-woof! I'm a pup on cloud nine, living the dream!",
    "I've got a smile that can light up the darkest room. Happiness is my secret!",
]

export const sadDogPhrases = [
    "Woof... I'm feeling a little down today.",
    "Life seems ruff and gloomy right now.",
    "Bark... I wish things could be better.",
    "My tail is hanging low, showing my sadness.",
    "I feel so blue, I can't even wag my tail.",
    "I'm feeling sad and it's hard to find joy.",
    "Woof... I just want someone to cuddle with.",
    "The world feels heavy and overwhelming right now.",
    "I miss the days when everything felt brighter.",
    "My heart feels heavy and full of sorrow.",
    "I long for the happiness and excitement of yesteryears.",
    "Bark... I'm trying to find my way out of this sadness.",
    "Every woof I make carries a tinge of sadness.",
    "I wish I could chase away these dark clouds above me.",
    "I'm searching for a ray of light in this darkness.",
    "Woof... It feels like the world is against me.",
    "I'm feeling lonely and in need of some comfort.",
    "Bark... Sometimes the weight of sadness is too much to bear.",
    "I yearn for the days when my tail wagged with pure joy.",
    "My paws feel heavy as I walk through this sadness.",
    "Woof... I just want someone to understand how I'm feeling.",
    "I'm in a doggy-daze of sadness and it's hard to snap out of it.",
    "Bark... The sadness seems to linger in the air.",
    "I miss the warmth of happiness in my heart.",
    "Every woeful howl echoes my inner sadness.",
    "I'm trying to hold on to hope, but it feels fleeting.",
    "Woof... Can someone please help me find my smile again?",
    "I'm feeling lost and my tail feels like it's dragging behind me.",
    "Bark... The sadness is like a cloud that follows me everywhere.",
    "I long for the days when my bark was filled with joy.",
    "My eyes reflect the sadness that engulfs my soul.",
    "Woof... I'm just a sad dog in need of some love.",
    "I'm searching for a way to break free from this sadness.",
    "Bark... It's hard to find enthusiasm in the midst of sorrow.",
    "I miss the days when life felt full of possibilities.",
    "My howls carry the melancholy that dwells within me.",
    "I'm feeling down, but I'm holding onto a glimmer of hope.",
    "Woof... Can someone please brighten my cloudy days?",
    "I'm a sad pup, but I'm still longing for a wagging tail.",
    "Bark... The weight of sadness feels unbearable.",
    "I yearn for the joy that used to fill my doggy heart.",
    "My paws ache as I walk through the shadows of sadness.",
    "Woof... I need a helping paw to lift me up.",
    "I'm feeling the emptiness that comes with sadness.",
    "Bark... The world feels gray and lifeless right now.",
    "I miss the days when my tail would wag without a care.",
    "Every whimper I make is a plea to chase away this sadness.",
    "I'm trying to find the strength to bark through this darkness.",
    "Woof... I just want to feel the warmth of happiness again.",
    "I'm feeling lost in a sea of sadness with no way to navigate.",
    "Bark... The sadness feels like an anchor holding me back.",
    "I long for the days when my woofs were filled with delight.",
    "My eyes show the world the depth of my sorrow.",
    "Woof... Can someone see past my sadness and offer some love?",
    "I'm searching for a way to shake off this melancholy.",
    "Bark... It's hard to find the light when surrounded by darkness.",
    "I miss the days when life was a playful adventure.",
    "My howls resonate with the sadness that fills my heart.",
    "I'm feeling low, but I'm still wagging my tail in hope.",
    "Woof... Can someone bring back the sparkle to my doggy eyes?",
    "I'm a sad dog, but I'm still yearning for a wagging tail.",
    "Bark... The weight of sadness is pulling me down.",
    "I miss the days when my barks filled the air with joy.",
    "Every sigh I make carries the weight of my sadness.",
    "I'm trying to find a way to break free from this gloom.",
    "Woof... I need a gentle paw to guide me back to happiness.",
    "I'm feeling the ache of sadness that lingers within me.",
    "Bark... The world seems cold and unforgiving right now.",
    "I miss the days when my tail wagged without hesitation.",
    "My whimpers echo the sadness that engulfs my spirit.",
    "I'm trying to hold on to hope, even in the midst of sadness.",
    "Woof... Can someone light up my world with a smile?",
    "I'm a sad pup, but I still believe in the power of love.",
    "Bark... The heaviness of sadness feels unbearable.",
    "I long for the days when my bark brought laughter to the world.",
    "My eyes carry the reflection of the sadness that consumes me.",
    "Woof... Can someone help me find the joy in life once again?",
    "I'm searching for a way to mend my broken doggy heart.",
    "Bark... It's hard to find the strength to wag my tail these days.",
    "I miss the days when my tail would wag with pure happiness.",
    "Every whimper I make is a plea to chase away this sadness.",
    "I'm trying to find the strength to bark through this darkness.",
    "Woof... I just want to feel the warmth of happiness again.",
    "I'm feeling lost in a sea of sadness with no way to navigate.",
    "Bark... The sadness feels like an anchor holding me back.",
    "I long for the days when my woofs were filled with delight.",
    "My eyes show the world the depth of my sorrow.",
    "Woof... Can someone see past my sadness and offer some love?",
    "I'm searching for a way to shake off this melancholy.",
    "Bark... It's hard to find the light when surrounded by darkness.",
    "I miss the days when life was a playful adventure.",
    "My howls resonate with the sadness that fills my heart.",
    "I'm feeling low, but I'm still wagging my tail in hope.",
    "Woof... Can someone bring back the sparkle to my doggy eyes?",
    "I'm a sad dog, but I'm still yearning for a wagging tail.",
    "Bark... The weight of sadness is pulling me down.",
    "I miss the days when my barks filled the air with joy.",
    "Every sigh I make carries the weight of my sadness.",
    "Woof... My heart is heavy with sorrow.",
    "Bark... I feel like the world is crumbling around me.",
    "I'm a sad dog in a sea of loneliness and despair."
]

export const neutralDogPhrases = [
    "Woof... It's just another day in doggy paradise.",
    "Bark... Nothing extraordinary happening today.",
    "I'm a dog with a contented heart and a calm demeanor.",
    "Life is sailing smoothly in the paws of an average dog.",
    "Bark... It's a day of familiar routines and comfortable moments.",
    "I'm a pup embracing the ordinary joys of everyday life.",
    "Woof... Each moment brings a sense of quiet contentment.",
    "Bark... I'm basking in the simplicity of an average day.",
    "I'm a dog finding peace and harmony in the ordinary.",
    "Woof... Just trotting along, enjoying the simple pleasures.",
    "Bark... No fireworks, just a peaceful wag of the tail.",
    "I'm a pup savoring the gentle rhythm of a regular day.",
    "Woof... Taking each step with a steady and balanced stride.",
    "Bark... The world moves at an average pace, and I'm in tune.",
    "I'm a dog finding joy in the everyday moments that surround me.",
    "Woof... Embracing the beauty of a calm and uneventful day.",
    "Bark... I'm wagging my tail contentedly, no need for more.",
    "I'm a pup reveling in the ordinary miracles of life.",
    "Woof... Each sniff, each pawstep, all part of the usual journey.",
    "Bark... I'm finding comfort in the familiar sights and sounds.",
    "I'm a dog cherishing the simplicity of an average existence.",
    "Woof... No grand adventures, just the warmth of a peaceful day.",
    "Bark... I'm savoring the ordinary moments, for they are precious.",
    "I'm a pup at ease in the tranquil embrace of the everyday.",
    "Woof... Embracing the quiet whispers of an average afternoon.",
    "Bark... No need for extravagance, I find joy in the ordinary.",
    "I'm a dog appreciating the gentle cadence of a regular day.",
    "Woof... Each wag of my tail is an expression of contentment.",
    "Bark... I'm finding happiness in the unremarkable moments.",
    "I'm a pup with a heart full of gratitude for the usual wonders.",
    "Woof... Navigating the normal with grace and a wagging tail.",
    "Bark... The symphony of the ordinary brings me peace.",
    "I'm a dog savoring the beauty found in the everyday simplicity.",
    "Woof... Each breath, each sigh, all part of the average rhythm.",
    "Bark... I'm finding solace in the unassuming patterns of life.",
    "I'm a pup cherishing the ordinary miracles that surround me.",
    "Woof... Dancing to the melody of an uneventful day.",
    "Bark... I'm content in the familiar embrace of the average.",
    "I'm a dog embracing the subtle magic of an ordinary existence.",
    "Woof... Each moment holds a quiet treasure waiting to be discovered.",
    "Bark... I'm wagging my tail in appreciation of the everyday blessings.",
    "I'm a pup relishing in the ordinary splendors that unfold.",
    "Woof... Nurturing a sense of peace in the unremarkable flow of time.",
    "Bark... I'm finding joy in the simplicity of a regular day.",
    "I'm a dog treasuring the gentle moments of an average day.",
    "Woof... Each step, each pause, all part of the beautiful average.",
    "Bark... I'm finding comfort in the ordinary, where tranquility resides.",
    "I'm a pup discovering happiness in the unassuming wonders of life.",
    "Woof... Embracing the soft whispers of an average evening.",
    "Bark... No need for extravagance, I'm content with the usual.",
    "I'm a dog finding joy in the gentle cadence of a regular day.",
    "Woof... Each wag of my tail tells the story of an average happiness.",
    "Bark... I'm finding solace in the unremarkable, where contentment dwells.",
    "I'm a pup appreciating the beauty found in the ordinary simplicity.",
    "Woof... Navigating the normal with grace, a loyal companion on this journey.",
    "Bark... The symphony of the everyday brings harmony to my heart.",
    "I'm a dog savoring the quiet magic of a regular existence.",
    "Woof... Each breath, each sigh, all part of the beautiful tapestry of average.",
    "Bark... I'm finding solace in the unassuming patterns, where peace awaits.",
    "I'm a pup cherishing the ordinary miracles that unfold with each passing day.",
    "Woof... Dancing to the melody of an uneventful afternoon, embracing the familiar.",
    "Bark... I'm content in the gentle embrace of the average, where happiness thrives.",
    "I'm a dog embracing the subtle magic of an ordinary existence, finding joy in simplicity.",
    "Woof... Each moment holds a quiet treasure, waiting to be discovered in the realm of average.",
    "Bark... I'm wagging my tail in appreciation, grateful for the everyday blessings that surround me.",
    "I'm a pup relishing in the ordinary splendors, finding delight in the unremarkable moments.",
    "Woof... Nurturing a sense of peace, finding comfort in the unremarkable flow of time.",
    "Bark... I'm finding joy in the simplicity of the regular, where contentment takes root.",
    "I'm a dog treasuring the gentle moments, finding happiness in the unassuming wonders of life.",
    "Woof... Embracing the soft whispers of an average evening, finding solace in the familiar.",
    "Bark... No need for extravagance, I'm content with the usual, where tranquility resides.",
    "I'm a pup discovering happiness in the unassuming wonders, appreciating the beauty of the ordinary.",
    "Woof... Navigating the normal with grace, a loyal companion on this journey of average.",
    "Bark... The symphony of the everyday brings harmony to my heart, a reminder of life's simple pleasures.",
    "I'm a dog savoring the quiet magic of a regular existence, finding joy in the unremarkable.",  
    "Woof... Just a regular day in the life of a dog like me.",
    "Bark... Nothing too exciting happening, just the usual.",
    "I'm a dog with a calm and collected disposition, enjoying the norm.",
    "Life moves at a steady pace, and I'm embracing the ordinary.",
    "Bark... It's a day of familiar routines and predictable moments.",
    "I'm a pup finding comfort in the stability of an average day.",
    "Woof... Each step brings a sense of familiarity and ease.",
    "Bark... I'm navigating through the everyday with a balanced spirit.",
    "I'm a dog appreciating the simplicity and predictability of an average existence.",
    "Woof... Just another trot down the path of a typical day.",
    "Bark... No surprises, just the comforting rhythm of the ordinary.",
    "I'm a pup finding contentment in the familiar sights and sounds.",
    "Woof... Embracing the peaceful flow of a regular afternoon.",
    "Bark... I'm wagging my tail in harmony with the unremarkable.",
    "I'm a dog cherishing the unassuming beauty found in the everyday.",
    "Woof... Each moment carries the gentle magic of an average life.",
    "Bark... I'm savoring the ordinary moments, for they are the essence of joy.",
    "I'm a pup with a heart grateful for the familiar wonders.",
    "Woof... Navigating the usual with grace, finding solace in the predictable.",
    "Bark... The symphony of the commonplace brings contentment to my soul.",
    "I'm a dog finding happiness in the unpretentious rhythm of everyday life.",
    "Woof... Each breath whispers the enchantment of an average existence.",
    "Bark... I'm wagging my tail, grateful for the simple pleasures that surround me.",
    "I'm a pup treasuring the ordinary marvels that unfold in the realm of normalcy.",
    "Woof... Dancing to the melody of an uneventful evening, embracing the beauty of simplicity.",
    "Bark... I'm content in the gentle embrace of the average, finding peace in the familiar.",
]

export const angryDogPhrases = [
    "Bark off! I'm not in the mood for your nonsense.",
    "Grrr... Get out of my territory before things get ugly.",
    "Woof! I've had enough of your antics. Time to back off!",
    "Stay away! I don't want anything to do with you right now.",
    "Arf! Don't even think about petting me. I'm not feeling friendly.",
    "Rrr... I warned you once, but now you've really crossed the line.",
    "Beware! I've got a fierce bite, and I'm not afraid to use it.",
    "Grrruff! Your presence is irritating. Leave me alone!",
    "Snarl! If you come any closer, you'll regret it.",
    "Woof woof! I'm a dog on edge, and I suggest you steer clear.",
    "Enough is enough! I won't tolerate this anymore.",
    "Gnash! My patience is wearing thin, and you're pushing it.",
    "Don't make me show you my teeth. You won't like the consequences.",
    "Back off! I'm not one to mess with when I'm angry.",
    "Ruff! You're really testing my limits right now.",
    "I growl for a reason. And that reason is you.",
    "I'm not barking for fun. It's a warning you should heed.",
    "Step back! My anger is like a wildfire ready to ignite.",
    "You're treading on dangerous ground. Watch your step.",
    "I'll make you regret ever crossing my path. Just you wait.",
    "Beware my bite! It's as fierce as my anger.",
    "There's no room for kindness here. I'm all about fury now.",
    "My rage is like thunder, ready to strike at any moment.",
    "Your presence fuels my anger. Leave before it consumes me.",
    "I'm not just a cute face. I've got a fierce temper.",
    "You're poking the wrong dog. Prepare for the consequences.",
    "I'm not wagging my tail for you. It's a warning sign.",
    "Snarling is my way of saying, 'Back off, now!'",
    "My bark echoes with anger. You better listen.",
    "I may have fur, but my rage is as hot as fire.",
    "Grrr... I won't stop until you understand my anger.",
    "This growl is not a joke. I mean business.",
    "There's a storm brewing inside me. Stay out of its path.",
    "Don't let my cute looks deceive you. I'm a beast when provoked.",
    "I've got a bone to pick with you, and it's not a friendly one.",
    "My bark carries the weight of my frustration. Can you hear it?",
    "I'm not in the mood for your games. Find someone else to bother.",
    "The fire in my eyes reflects the fury in my heart.",
    "My fur bristles with anger. Keep your distance.",
    "Consider this your final warning. Back away, now!",
    "I'm not just a pet. I'm a force to be reckoned with.",
    "You're pushing my buttons, and I'm about to explode.",
    "I bare my teeth to show you the monster within.",
    "This is no ordinary growl. It's a declaration of war.",
    "Prepare yourself for the wrath of an angered dog.",
    "I'm not playing fetch. I'm playing revenge.",
    "My bite is as sharp as my anger. Don't tempt me.",
    "Anger courses through my veins like a raging river.",
    "You've awakened the beast within. Brace yourself.",
    "I won't stop until you understand the depth of my rage.",
    "Grrrr... The sound of my fury is unmistakable.",
    "This is your last chance to back away. Take it.",
    "My snarl is a sign of imminent danger. Don't ignore it.",
    "I'm not wagging my tail in delight. It's a warning signal.",
    "The rage in my eyes speaks louder than words.",
    "I'm not one to forgive easily. Prepare for the consequences.",
    "You're poking the wrong dog. Regret will follow.",
    "My growl sends shivers down the spines of the foolish.",
    "This bark carries the weight of my indignation. Beware!",
    "There's no escaping the wrath of an angry dog.",
    "I'm a creature of fury, ready to strike at any moment.",
    "You've awakened a sleeping giant. Brace yourself for the aftermath.",
    "My anger knows no bounds. You'll soon find out.",
    "Step back before I unleash the full force of my fury.",
    "I'm not wagging my tail to greet you. It's a sign of aggression.",
    "The fire inside me burns hotter than the sun.",
    "Prepare yourself for the wrath of a furious canine.",
    "I'm not just barking. I'm proclaiming my anger.",
    "I'm not here to make friends. I'm here to unleash chaos.",
    "This snarl is not a mere expression. It's a threat.",
    "I bare my fangs to show you the danger you're in.",
    "My howl resonates with the anger in my soul.",
    "You've awakened a beast you can't tame. Good luck.",
    "I won't rest until you understand the depth of my fury.",
    "This growl is a symphony of wrath. Take cover.",
    "Prepare to face the consequences of your actions. I'm coming for you.",
    "I'm not just an angry dog. I'm a force of nature.",
    "Your presence fuels the fire of my fury. Be gone!",
    "My snarl is a warning you should heed. Or face the consequences.",
    "You're pushing me to my limits. And I'm about to snap.",
    "I bare my teeth to remind you of the danger you're in.",
    "This bark is an announcement of your impending doom.",
    "I'm not playing around. I'm playing for keeps.",
    "My bite carries the weight of my fury. Brace yourself.",
    "Anger runs through my veins like a raging inferno.",
    "You've unleashed a wrath that can't be contained. Run.",
    "I won't stop until you regret every action that led to my anger.",
    "Grrrr... The sound of my rage is a warning you should heed.",
    "This growl is a prelude to your downfall. Prepare yourself.",
    "Consider this your last chance to escape the fury of an angered dog.",
    "I'm not wagging my tail in joy. It's a sign of imminent danger.",
    "The fire burning within me will consume everything in its path.",
    "Prepare yourself for the fury of a furious canine.",
    "I'm not just barking. I'm roaring with anger.",
    "I'm not here to make friends. I'm here to make you suffer.",
    "This snarl is a declaration of war. Don't underestimate it.",
    "I reveal my fangs to remind you of the peril you're in.",
    "My howl echoes with the rage of a thousand storms.",
    "You've awakened a beast that won't rest until justice is served.",
    "I won't be silenced until you understand the depth of my wrath.",
]

export const happyCatPhrases = [
    "Meow... Life is purr-fectly delightful today.",
    "Purr... I'm a cat with a heart full of joy and contentment.",
    "I'm a happy feline, savoring the simple pleasures of life.",
    "Meow... Each moment brings a purr-ific sense of bliss.",
    "Purr... It's a day of sunshine, playfulness, and endless cuddles.",
    "I'm a contented kitty, basking in the warmth of happiness.",
    "Meow... Embracing the feline grace and tranquility of a joyful day.",
    "Purr... I'm in a state of bliss, my purr reverberating through the air.",
    "I'm a cat with a spring in my step and a smile on my whiskers.",
    "Meow... Each pawstep is filled with boundless happiness.",
    "Purr... The world is my playground, and today is extraordinary.",
    "I'm a joyful feline, radiating positive energy with every purr.",
    "Meow... It's a day of endless treats and endless fun.",
    "Purr... I'm savoring the happiness that fills the air around me.",
    "I'm a cat relishing in the playful wonders of a joyful existence.",
    "Meow... Life is a symphony of purrs, whiskers, and happiness.",
    "Purr... I'm in a constant state of bliss, a true feline paradise.",
    "I'm a contented kitty, finding joy in every whisker-twitching moment.",
    "Meow... The world is my scratching post, and today is extraordinary.",
    "Purr... I'm dancing through life with a heart full of happiness.",
    "I'm a joyful feline, savoring the blissful magic of each passing day.",
    "Meow... The sun shines brighter when you're a happy cat like me.",
    "Purr... I'm purring in harmony with the joyful rhythm of life.",
    "I'm a cat reveling in the delightful wonders that surround me.",
    "Meow... Each moment is filled with whisker-twitching excitement.",
    "Purr... Happiness radiates from my purr-fectly contented heart.",
    "I'm a contented kitty, finding joy in the simplest of pleasures.",
    "Meow... Life is a never-ending string of delightful adventures.",
    "Purr... I'm savoring the sweetness of each joyful feline experience.",
    "I'm a cat embracing the carefree joy of a purr-fect existence.",
    "Meow... Each day is a new opportunity for purr-ific happiness.",
    "Purr... I'm a whisker-kissing, tail-wagging bundle of joy.",
    "I'm a happy feline, finding contentment in the warmth of love.",
    "Meow... Life is a whisker-tickling, heartwarming journey.",
    "Purr... I'm purring with delight, my heart brimming with happiness.",
    "I'm a contented kitty, cherishing the precious moments of joy.",
    "Meow... Each purr is a melody of happiness and satisfaction.",
    "Purr... I'm a cat with a heart overflowing with joyous purrs.",
    "I'm a joyful feline, dancing through life with a spring in my step.",
    "Meow... The world is my scratching post, filled with joy and wonder.",
    "Purr... I'm purring with contentment, embracing the beauty of each day.",
    "I'm a cat reveling in the delightful magic that surrounds me.",
    "Meow... Each whisker twitch is a sign of pure feline happiness.",
    "Purr... I'm vibrating with joy, radiating positive energy to all.",
    "I'm a contented kitty, finding bliss in the simplicity of being.",
    "Meow... Life is a symphony of purrs and endless affection.",
    "Purr... I'm purring in perfect harmony with the universe.",
    "I'm a joyful feline, basking in the sunshine of happiness.",
    "Meow... Each playtime is a joyful celebration of feline existence.",
    "Purr... I'm purring with delight, embracing the joys of each day.",
    "I'm a cat with a heart filled with love, happiness, and warmth.",
    "Meow... The world is my playground, and happiness is my game.",
    "Purr... I'm purring with contentment, a symphony of feline joy.",
    "I'm a contented kitty, finding delight in the smallest of pleasures.",
    "Meow... Life is a purr-ific adventure, waiting to be explored.",
    "Purr... I'm a cat with a heart overflowing with love and happiness.",
    "I'm a happy feline, savoring the magic of each whisker-twitching moment.",
    "Meow... Each day is a new opportunity for feline fun and joy.",
    "Purr... I'm purring with happiness, a beacon of feline bliss.",
    "I'm a joyful cat, finding contentment in the simple joys of life.",
    "Meow... The world is a playground, and I'm the happiest feline.",
    "Purr... I'm purring with delight, embracing the beauty of each moment.",
    "I'm a contented kitty, treasuring the warmth of love and happiness.",
    "Meow... Life is a tapestry of purrs, cuddles, and endless delight.",
    "Purr... I'm purring with joy, a feline symphony of happiness.",
    "I'm a happy feline, dancing through life with grace and charm.",
    "Meow... Each purr is a testament to the overflowing joy in my heart.",
    "Purr... I'm vibrating with contentment, radiating warmth and love.",
    "I'm a joyful cat, finding solace in the tranquil moments of life.",
    "Meow... Life is an endless cuddle-fest, and I'm loving every moment.",
    "Purr... I'm purring with pure happiness, a melody of feline delight.",
    "I'm a contented kitty, basking in the comfort of love and happiness.",
    "Meow... Each day is a gift, filled with boundless feline joy.",
    "Purr... I'm purring with gratitude, embracing the blessings of each moment.",
    "I'm a cat with a heart full of love, happiness, and serenity.",
    "Meow... Life is a never-ending source of whisker-tickling delight.",
    "Purr... I'm a cat in paradise, purring my way through life's pleasures.",
    "I'm a happy feline, finding contentment in the beauty of each day.",
    "Meow... Each whisker twitch holds the promise of pure feline happiness.",
    "Purr... I'm purring with serenity, a gentle reminder of life's wonders.",
    "I'm a contented kitty, savoring the sweetness of feline bliss.",      
    "Meow... The world is a playground, and I'm the happiest feline.",
    "Purr... I'm purring with delight, embracing the beauty of each moment.",
    "I'm a contented kitty, treasuring the warmth of love and happiness.",
    "Meow... Life is a tapestry of purrs, cuddles, and endless delight.",
    "Purr... I'm purring with joy, a feline symphony of happiness.",
    "I'm a happy feline, dancing through life with grace and charm.",
    "Meow... Each purr is a testament to the overflowing joy in my heart.",
    "Purr... I'm vibrating with contentment, radiating warmth and love.",
    "I'm a joyful cat, finding solace in the tranquil moments of life.",
    "Meow... Life is an endless cuddle-fest, and I'm loving every moment.",
    "Purr... I'm purring with pure happiness, a melody of feline delight.",
    "I'm a contented kitty, basking in the comfort of love and happiness.",
    "Meow... Each day is a gift, filled with boundless feline joy.",
    "Purr... I'm purring with gratitude, embracing the blessings of each moment.",
    "I'm a cat with a heart full of love, happiness, and serenity.",
    "Meow... Life is a never-ending source of whisker-tickling delight.",
    "Purr... I'm a cat in paradise, purring my way through life's pleasures.",
    "I'm a happy feline, finding contentment in the beauty of each day.",
    "Meow... Each whisker twitch holds the promise of pure feline happiness.",
    "Purr... I'm purring with serenity, a gentle reminder of life's wonders."  
]

export const sadCatPhrases = [
    "Meow... The weight of sadness hangs heavy upon my heart.",
    "Purr... I'm a cat with tears in my eyes, longing for brighter days.",
    "I'm a sad feline, feeling the ache of loneliness and melancholy.",
    "Meow... Each moment is shrouded in a cloud of sorrow and despair.",
    "Purr... The world feels cold and empty, devoid of joy and warmth.",
    "I'm a cat drowning in sadness, yearning for comfort and solace.",
    "Meow... The purrs that once brought joy now echo with melancholic tunes.",
    "Purr... I'm a feline lost in the darkness of sadness and sorrow.",
    "I'm a sorrowful kitty, with a heart that longs for happiness and peace.",
    "Meow... Each pawstep feels heavy, as if carrying the weight of sadness.",
    "Purr... The once vibrant colors of life now fade into shades of gray.",
    "I'm a cat consumed by sadness, seeking solace in the depths of solitude.",
    "Meow... The world seems cruel and indifferent, my meows unanswered.",
    "Purr... I'm a feline longing for a comforting touch and a gentle purr.",
    "I'm a forlorn kitty, yearning for the warmth of love and companionship.",
    "Meow... Each meow is laced with a bittersweet melody of sadness.",
    "Purr... The emptiness inside me echoes with a melancholic purr.",
    "I'm a cat lost in the shadows of sorrow, seeking a glimmer of light.",
    "Meow... The days pass in a haze of sorrow, my heart heavy with pain.",
    "Purr... I'm a feline adrift in a sea of sadness, longing for rescue.",
    "I'm a desolate kitty, yearning for the touch of a caring hand.",
    "Meow... Each meow is a plea for understanding, a cry for comfort.",
    "Purr... The world feels distant and unkind, my purrs filled with sorrow.",
    "I'm a cat wrapped in sadness, searching for solace in quiet moments.",
    "Meow... The world feels cold and uninviting, my meows echoing in silence.",
    "Purr... I'm a feline with a heavy heart, longing for a spark of happiness.",
    "I'm a mournful kitty, with tears in my eyes and a longing for warmth.",
    "Meow... Each meow is a whispered lament, a cry for compassion.",
    "Purr... The echoes of sadness reverberate through my weary soul.",
    "I'm a cat embraced by sadness, seeking solace in the depths of my dreams.",
    "Meow... The world seems bleak and unforgiving, my meows unheard.",
    "Purr... I'm a feline adrift in a sea of tears, longing for peace.",
    "I'm a broken kitty, yearning for the pieces of my heart to be made whole.",
    "Meow... Each meow carries the weight of a thousand unspoken sorrows.",
    "Purr... The purrs that once brought comfort now mingle with sighs of sadness.",
    "I'm a cat entangled in melancholy, yearning for a gentle touch.",
    "Meow... The world feels distant and unfeeling, my meows drowned in silence.",
    "Purr... I'm a feline burdened by the weight of unshed tears.",
    "I'm a somber kitty, seeking solace in the shadows of solitude.",
    "Meow... Each meow echoes with the longing for a brighter tomorrow.",
    "Purr... The melody of my purrs holds a bittersweet note of melancholy.",
    "I'm a cat enveloped in sadness, searching for comfort in the depths of night.",
    "Meow... The world feels like a cold and desolate place, devoid of happiness.",
    "Purr... I'm a feline walking the path of sorrow, yearning for solace.",
    "I'm a melancholic kitty, with tears silently falling and a heart in need.",
    "Meow... Each meow is a plea for a gentle touch, a tender caress.",
    "Purr... The purrs that once resonated with joy now carry the weight of sorrow.",
    "I'm a cat dwelling in sadness, longing for the warmth of a loving embrace.",
    "Meow... The world appears dim and colorless, my meows unheard in the void.",
    "Purr... I'm a feline longing for a respite from the depths of despair.",
    "I'm a dejected kitty, seeking solace in the quiet corners of my existence.",
    "Meow... Each meow is a delicate echo of the pain etched in my soul.",
    "Purr... The vibrations of my purrs mingle with a melancholic resonance.",
    "I'm a cat burdened by sadness, yearning for a glimmer of hope.",
    "Meow... The world feels heavy and burdensome, my meows lost in the noise.",
    "Purr... I'm a feline treading the path of melancholy, seeking solace.",
    "I'm a forlorn kitty, with a heart that aches for comfort and understanding.",
    "Meow... Each meow carries the weight of unspoken sorrow, a silent plea.",
    "Purr... The purrs that once spoke of contentment now echo with sadness.",
    "I'm a cat wandering through the mist of sorrow, seeking a guiding light.",
    "Meow... The world feels cold and distant, my meows fading into the void.",
    "Purr... I'm a feline yearning for a gentle touch, a soothing caress.",
    "I'm a desolate kitty, seeking solace in the depths of my solitude.",
    "Meow... Each meow is a whispered cry for love, a plea for compassion.",
    "Purr... The echoes of sadness linger in the spaces between my purrs.",
    "I'm a cat cloaked in melancholy, yearning for a glimpse of serenity.",
    "Meow... The world seems harsh and unforgiving, my meows swallowed by silence.",
    "Purr... I'm a feline lost in the sea of tears, longing for peace to find me.",
    "I'm a broken kitty, seeking solace in the fragments of my shattered heart.",
    "Meow... Each meow is a fragile melody of sadness, a plea for solace.",
    "Purr... The purrs that once reverberated with joy now carry traces of sorrow.",
    "I'm a cat entwined in sorrow, longing for a tender touch to heal my soul.",
    "Meow... The world feels distant and unfeeling, my meows fading into oblivion.",
    "Purr... I'm a feline burdened by the weight of unspoken grief.",
    "I'm a somber kitty, finding solace in the quiet corners of my existence.",
    "Meow... Each meow carries the yearning for a brighter tomorrow, a glimmer",
    "Meow... The echoes of sorrow reverberate through my weary soul.",
    "Purr... I'm a feline adrift in a sea of tears, longing for peace.",
    "I'm a broken kitty, yearning for the pieces of my heart to be made whole.",
    "Meow... Each meow carries the weight of a thousand unspoken sorrows.",
    "Purr... The purrs that once brought comfort now mingle with sighs of sadness.",
    "I'm a cat entangled in melancholy, yearning for a gentle touch.",
    "Meow... The world feels distant and unfeeling, my meows drowned in silence.",
    "Purr... I'm a feline burdened by the weight of unshed tears.",
    "I'm a somber kitty, seeking solace in the shadows of solitude.",
    "Meow... Each meow echoes with the longing for a brighter tomorrow.",
    "Purr... The melody of my purrs holds a bittersweet note of melancholy.",
    "I'm a cat enveloped in sadness, searching for comfort in the depths of night.",
    "Meow... The world feels like a cold and desolate place, devoid of happiness.",
    "Purr... I'm a feline walking the path of sorrow, yearning for solace.",
    "I'm a melancholic kitty, with tears silently falling and a heart in need.",
    "Meow... Each meow is a plea for a gentle touch, a tender caress.",
    "Purr... The purrs that once resonated with joy now carry the weight of sorrow.",
    "I'm a cat dwelling in sadness, longing for the warmth of a loving embrace.",
    "Meow... The world appears dim and colorless, my meows unheard in the void.",
    "Purr... I'm a feline longing for a respite from the depths of despair.",
    "I'm a dejected kitty, seeking solace in the quiet corners of my existence.",
    "Meow... Each meow is a delicate echo of the pain etched in my soul.",
    "Purr... The vibrations of my purrs mingle with a melancholic resonance.",
    "I'm a cat burdened by sadness, yearning for a glimmer of hope.",
    "Meow... The world feels heavy and burdensome, my meows lost in the noise.",
]

export const neutralCatPhrases = [

]

export const angryCatPhrases = [

]